// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220625121044_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01e3903b-fabf-43bf-ad1f-550eee74f6bc"),
                            Name = "Tesco"
                        },
                        new
                        {
                            Id = new Guid("6dd0b608-04a8-42e1-bcaf-971367bd8302"),
                            Name = "ING"
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1ae2"),
                            Name = "Porche"
                        },
                        new
                        {
                            Id = new Guid("c6aee1bb-a570-49f4-b3b8-6448e336c42b"),
                            Name = "BMW"
                        },
                        new
                        {
                            Id = new Guid("be8a467f-0f93-4993-b516-5ba58e88abf0"),
                            Name = "Nike"
                        },
                        new
                        {
                            Id = new Guid("daa4e8ca-929f-43f1-816d-c580f11ff905"),
                            Name = "Addidas"
                        });
                });

            modelBuilder.Entity("Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1c070edb-5e19-43f7-9727-cbc585524ebb"),
                            CompanyId = new Guid("01e3903b-fabf-43bf-ad1f-550eee74f6bc"),
                            Completed = false,
                            Deadline = new DateTime(2022, 7, 22, 9, 0, 0, 898, DateTimeKind.Local),
                            Name = "External portal"
                        },
                        new
                        {
                            Id = new Guid("c76cab95-4a52-4344-a803-ab78e06c59fd"),
                            CompanyId = new Guid("01e3903b-fabf-43bf-ad1f-550eee74f6bc"),
                            Completed = false,
                            Deadline = new DateTime(2022, 7, 12, 15, 0, 0, 898, DateTimeKind.Local),
                            Name = "Main project"
                        },
                        new
                        {
                            Id = new Guid("5bb3e3fb-35e6-4d5a-b2ba-f5da9eeac775"),
                            CompanyId = new Guid("6dd0b608-04a8-42e1-bcaf-971367bd8302"),
                            Completed = false,
                            Deadline = new DateTime(2022, 8, 10, 12, 0, 0, 898, DateTimeKind.Local),
                            Name = "Proctocol Update"
                        },
                        new
                        {
                            Id = new Guid("2593faee-7b0d-4a56-81d8-9466c82a2ac4"),
                            CompanyId = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1ae2"),
                            Completed = false,
                            Deadline = new DateTime(2022, 7, 1, 16, 0, 0, 898, DateTimeKind.Local),
                            Name = "Car Preview"
                        },
                        new
                        {
                            Id = new Guid("59dedd79-bce9-4c6e-8004-e91196dc7d3b"),
                            CompanyId = new Guid("c6aee1bb-a570-49f4-b3b8-6448e336c42b"),
                            Completed = false,
                            Deadline = new DateTime(2022, 6, 28, 16, 0, 0, 898, DateTimeKind.Local),
                            Name = "SSO Auth"
                        },
                        new
                        {
                            Id = new Guid("d8d28769-5d6b-4f36-b1e2-6df9f9fec2a6"),
                            CompanyId = new Guid("c6aee1bb-a570-49f4-b3b8-6448e336c42b"),
                            Completed = false,
                            Deadline = new DateTime(2022, 7, 5, 18, 0, 0, 898, DateTimeKind.Local),
                            Name = "Project Update"
                        },
                        new
                        {
                            Id = new Guid("b23817f7-1eae-4de4-bd4a-a1d8544604ee"),
                            CompanyId = new Guid("c6aee1bb-a570-49f4-b3b8-6448e336c42b"),
                            Completed = false,
                            Deadline = new DateTime(2022, 7, 9, 11, 0, 0, 898, DateTimeKind.Local),
                            Name = "Admin Panel"
                        },
                        new
                        {
                            Id = new Guid("7f650e8b-f17c-48e5-a343-e7658d9feb39"),
                            CompanyId = new Guid("be8a467f-0f93-4993-b516-5ba58e88abf0"),
                            Completed = false,
                            Deadline = new DateTime(2022, 8, 1, 7, 0, 0, 898, DateTimeKind.Local),
                            Name = "Shoe Designer Tool"
                        },
                        new
                        {
                            Id = new Guid("0d9fb1ae-7e9a-4c07-9112-56199bb9a6f1"),
                            CompanyId = new Guid("daa4e8ca-929f-43f1-816d-c580f11ff905"),
                            Completed = true,
                            Deadline = new DateTime(2022, 7, 14, 10, 0, 0, 898, DateTimeKind.Local),
                            Name = "Site update"
                        });
                });

            modelBuilder.Entity("Domain.TimeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("LoggedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("TimeLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a00"),
                            CreatedAt = new DateTime(2022, 7, 14, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 30L,
                            ProjectId = new Guid("1c070edb-5e19-43f7-9727-cbc585524ebb")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a01"),
                            CreatedAt = new DateTime(2022, 7, 15, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 60L,
                            ProjectId = new Guid("1c070edb-5e19-43f7-9727-cbc585524ebb")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a02"),
                            CreatedAt = new DateTime(2022, 7, 16, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 90L,
                            ProjectId = new Guid("1c070edb-5e19-43f7-9727-cbc585524ebb")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a03"),
                            CreatedAt = new DateTime(2022, 7, 17, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 60L,
                            ProjectId = new Guid("1c070edb-5e19-43f7-9727-cbc585524ebb")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a04"),
                            CreatedAt = new DateTime(2022, 7, 18, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 100L,
                            ProjectId = new Guid("1c070edb-5e19-43f7-9727-cbc585524ebb")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a05"),
                            CreatedAt = new DateTime(2022, 7, 19, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 20L,
                            ProjectId = new Guid("1c070edb-5e19-43f7-9727-cbc585524ebb")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a06"),
                            CreatedAt = new DateTime(2022, 7, 20, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 50L,
                            ProjectId = new Guid("1c070edb-5e19-43f7-9727-cbc585524ebb")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a07"),
                            CreatedAt = new DateTime(2022, 7, 22, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 60L,
                            ProjectId = new Guid("1c070edb-5e19-43f7-9727-cbc585524ebb")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a08"),
                            CreatedAt = new DateTime(2022, 7, 23, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 40L,
                            ProjectId = new Guid("1c070edb-5e19-43f7-9727-cbc585524ebb")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a10"),
                            CreatedAt = new DateTime(2022, 7, 14, 11, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 120L,
                            ProjectId = new Guid("c76cab95-4a52-4344-a803-ab78e06c59fd")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a11"),
                            CreatedAt = new DateTime(2022, 7, 15, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 60L,
                            ProjectId = new Guid("c76cab95-4a52-4344-a803-ab78e06c59fd")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a12"),
                            CreatedAt = new DateTime(2022, 7, 16, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 90L,
                            ProjectId = new Guid("c76cab95-4a52-4344-a803-ab78e06c59fd")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a13"),
                            CreatedAt = new DateTime(2022, 7, 17, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 120L,
                            ProjectId = new Guid("c76cab95-4a52-4344-a803-ab78e06c59fd")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a14"),
                            CreatedAt = new DateTime(2022, 7, 18, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 130L,
                            ProjectId = new Guid("c76cab95-4a52-4344-a803-ab78e06c59fd")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a15"),
                            CreatedAt = new DateTime(2022, 7, 19, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 200L,
                            ProjectId = new Guid("c76cab95-4a52-4344-a803-ab78e06c59fd")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a16"),
                            CreatedAt = new DateTime(2022, 7, 20, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 160L,
                            ProjectId = new Guid("c76cab95-4a52-4344-a803-ab78e06c59fd")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a17"),
                            CreatedAt = new DateTime(2022, 7, 22, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 210L,
                            ProjectId = new Guid("c76cab95-4a52-4344-a803-ab78e06c59fd")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a18"),
                            CreatedAt = new DateTime(2022, 7, 23, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 240L,
                            ProjectId = new Guid("c76cab95-4a52-4344-a803-ab78e06c59fd")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a19"),
                            CreatedAt = new DateTime(2022, 7, 24, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 60L,
                            ProjectId = new Guid("c76cab95-4a52-4344-a803-ab78e06c59fd")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a20"),
                            CreatedAt = new DateTime(2022, 7, 14, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 120L,
                            ProjectId = new Guid("5bb3e3fb-35e6-4d5a-b2ba-f5da9eeac775")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a21"),
                            CreatedAt = new DateTime(2022, 7, 15, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 60L,
                            ProjectId = new Guid("5bb3e3fb-35e6-4d5a-b2ba-f5da9eeac775")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a22"),
                            CreatedAt = new DateTime(2022, 7, 16, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 90L,
                            ProjectId = new Guid("5bb3e3fb-35e6-4d5a-b2ba-f5da9eeac775")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a30"),
                            CreatedAt = new DateTime(2022, 7, 14, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 120L,
                            ProjectId = new Guid("2593faee-7b0d-4a56-81d8-9466c82a2ac4")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a31"),
                            CreatedAt = new DateTime(2022, 7, 15, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 60L,
                            ProjectId = new Guid("2593faee-7b0d-4a56-81d8-9466c82a2ac4")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a40"),
                            CreatedAt = new DateTime(2022, 7, 14, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 20L,
                            ProjectId = new Guid("59dedd79-bce9-4c6e-8004-e91196dc7d3b")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a41"),
                            CreatedAt = new DateTime(2022, 7, 13, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 35L,
                            ProjectId = new Guid("59dedd79-bce9-4c6e-8004-e91196dc7d3b")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a42"),
                            CreatedAt = new DateTime(2022, 7, 14, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 150L,
                            ProjectId = new Guid("1c070edb-5e19-43f7-9727-cbc585524ebb")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a43"),
                            CreatedAt = new DateTime(2022, 7, 18, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 135L,
                            ProjectId = new Guid("59dedd79-bce9-4c6e-8004-e91196dc7d3b")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a44"),
                            CreatedAt = new DateTime(2022, 7, 20, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 170L,
                            ProjectId = new Guid("59dedd79-bce9-4c6e-8004-e91196dc7d3b")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a45"),
                            CreatedAt = new DateTime(2022, 7, 21, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 120L,
                            ProjectId = new Guid("59dedd79-bce9-4c6e-8004-e91196dc7d3b")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a46"),
                            CreatedAt = new DateTime(2022, 7, 22, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 90L,
                            ProjectId = new Guid("59dedd79-bce9-4c6e-8004-e91196dc7d3b")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a47"),
                            CreatedAt = new DateTime(2022, 7, 24, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 100L,
                            ProjectId = new Guid("59dedd79-bce9-4c6e-8004-e91196dc7d3b")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a50"),
                            CreatedAt = new DateTime(2022, 7, 1, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 35L,
                            ProjectId = new Guid("d8d28769-5d6b-4f36-b1e2-6df9f9fec2a6")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a51"),
                            CreatedAt = new DateTime(2022, 7, 2, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 55L,
                            ProjectId = new Guid("d8d28769-5d6b-4f36-b1e2-6df9f9fec2a6")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a52"),
                            CreatedAt = new DateTime(2022, 7, 3, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 115L,
                            ProjectId = new Guid("d8d28769-5d6b-4f36-b1e2-6df9f9fec2a6")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a53"),
                            CreatedAt = new DateTime(2022, 7, 5, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 45L,
                            ProjectId = new Guid("d8d28769-5d6b-4f36-b1e2-6df9f9fec2a6")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a54"),
                            CreatedAt = new DateTime(2022, 7, 8, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 40L,
                            ProjectId = new Guid("d8d28769-5d6b-4f36-b1e2-6df9f9fec2a6")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a55"),
                            CreatedAt = new DateTime(2022, 7, 9, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 50L,
                            ProjectId = new Guid("d8d28769-5d6b-4f36-b1e2-6df9f9fec2a6")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a60"),
                            CreatedAt = new DateTime(2022, 6, 1, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 480L,
                            ProjectId = new Guid("b23817f7-1eae-4de4-bd4a-a1d8544604ee")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a61"),
                            CreatedAt = new DateTime(2022, 6, 8, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 300L,
                            ProjectId = new Guid("b23817f7-1eae-4de4-bd4a-a1d8544604ee")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a62"),
                            CreatedAt = new DateTime(2022, 6, 13, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 360L,
                            ProjectId = new Guid("b23817f7-1eae-4de4-bd4a-a1d8544604ee")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a63"),
                            CreatedAt = new DateTime(2022, 6, 15, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 300L,
                            ProjectId = new Guid("b23817f7-1eae-4de4-bd4a-a1d8544604ee")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a70"),
                            CreatedAt = new DateTime(2022, 7, 1, 10, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 120L,
                            ProjectId = new Guid("7f650e8b-f17c-48e5-a343-e7658d9feb39")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a80"),
                            CreatedAt = new DateTime(2022, 7, 2, 15, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 180L,
                            ProjectId = new Guid("0d9fb1ae-7e9a-4c07-9112-56199bb9a6f1")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a81"),
                            CreatedAt = new DateTime(2022, 7, 4, 15, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 240L,
                            ProjectId = new Guid("0d9fb1ae-7e9a-4c07-9112-56199bb9a6f1")
                        },
                        new
                        {
                            Id = new Guid("01cfd494-fca0-4a3f-9a2d-1763d62f1a82"),
                            CreatedAt = new DateTime(2022, 7, 5, 15, 0, 0, 898, DateTimeKind.Local),
                            LoggedMinutes = 210L,
                            ProjectId = new Guid("0d9fb1ae-7e9a-4c07-9112-56199bb9a6f1")
                        });
                });

            modelBuilder.Entity("Domain.Project", b =>
                {
                    b.HasOne("Domain.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.TimeLog", b =>
                {
                    b.HasOne("Domain.Project", null)
                        .WithMany("Logs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Company", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Domain.Project", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
